sudo: required
services: 
  - docker

before_install:
  - docker build -t milkomilchev/docker-react -f Dockerfile.dev .


script: 
  - docker run -e CI=true milkomilchev/docker-react npm run test

language: generic
